1.Write a program to distinguish between Array Indexing and Fancy Indexing.

In [66]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])
#Array(Simple) Indexing
ai=arr1[3]
print("Array Indexing: ",ai)
#Fancy Indexing
fi=arr1[[2,4,6,8]]
print("Fancy Indexing: ",fi)


Array Indexing:  4
Fancy Indexing:  [3 5 7 9]


2.Execute the 2D array Slicing.

In [67]:
import numpy as np
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[1][1:5])

[ 8  9 10 11]


3.Create the 5-Dimensional arrays using ‘ndmin’.

In [68]:
import numpy as np
arr1=np.array([9,8,7,6],ndmin=5)
print("The 5 dimensional array using ndmin is : ",arr1)


The 5 dimensional array using ndmin is :  [[[[[9 8 7 6]]]]]


4.Reshape the array from 1-D to 2-D array.

In [69]:
import numpy as np
arr=np.array([0,9,8,7,6,5,4,3,2,1])
print("The original array :",arr)
reshapearr=arr.reshape(2,5)
print("Array after reshapeing : \n",reshapearr)

The original array : [0 9 8 7 6 5 4 3 2 1]
Array after reshapeing : 
 [[0 9 8 7 6]
 [5 4 3 2 1]]


5.Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [70]:
import numpy as np
arr1=np.array([00,11,22,33,44,55,66,77,88,99])
print("First array : ",arr1)
arr2=np.array([10,20,30,40,50,60,70,80,90,100])
print("Second array : ",arr2)

#Using stack
sarr=np.stack((arr1,arr2))
print("\nArrays after using stack : \n",sarr)

#Using hstack
harr=np.hstack((arr1,arr2))
print("\nArrays after using hstack : \n",harr)

#Using vstack 
varray=np.vstack((arr1,arr2))
print("\nArrays after using vstack : \n",varray)

#Using dstack
darray=np.dstack((arr1,arr2))
print("\nArrays after using dstack :\n",darray)


First array :  [ 0 11 22 33 44 55 66 77 88 99]
Second array :  [ 10  20  30  40  50  60  70  80  90 100]

Arrays after using stack : 
 [[  0  11  22  33  44  55  66  77  88  99]
 [ 10  20  30  40  50  60  70  80  90 100]]

Arrays after using hstack : 
 [  0  11  22  33  44  55  66  77  88  99  10  20  30  40  50  60  70  80
  90 100]

Arrays after using vstack : 
 [[  0  11  22  33  44  55  66  77  88  99]
 [ 10  20  30  40  50  60  70  80  90 100]]

Arrays after using dstack :
 [[[  0  10]
  [ 11  20]
  [ 22  30]
  [ 33  40]
  [ 44  50]
  [ 55  60]
  [ 66  70]
  [ 77  80]
  [ 88  90]
  [ 99 100]]]


6.Perform the searchsort method in Numpy array.

In [71]:
import numpy as np
arr=np.array([12,23,34,45,56,67,78])

sarr=np.searchsorted(arr,[45,56,78,12])
print("Search Sort : ",sarr)

sarray=np.searchsorted(arr,23,side='left')
print("(using side) : ",sarray)

Search Sort :  [3 4 6 0]
(using side) :  1


7.Create Numpy Structured array using your domain features.

In [72]:
import numpy as np
me=np.array([('Rojal','Online Game Rental Site',2347249)],
            dtype=[('name',(np.str_,10)),('age',np.str_,100),('registerno',np.int32)])
print("My domain features : ",me)
    

My domain features :  [('Rojal', 'Online Game Rental Site', 2347249)]


8.Create Data frame using List and Dictionary.

In [73]:
import pandas as pd
#Dataframe using Dictionary
df={
    'Books':['Aarachar','Harry Potter 1','Percy Jackson','Chemmeen'],
    'Year':[2012,1997,2010,1956]
}
mybooks=pd.DataFrame(df)
print(mybooks)

#DataFrame using list
mylist=[2012,1997,2010,1956]
mydata=pd.DataFrame(mylist,index=['a','b','c','d'],
                    columns=['Years'])
print("\n\n",mydata)

            Books  Year
0        Aarachar  2012
1  Harry Potter 1  1997
2   Percy Jackson  2010
3        Chemmeen  1956


    Years
a   2012
b   1997
c   2010
d   1956


9.Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [74]:
import pandas as pd
import numpy as np
Games={'Title':['Alan Wake','Assassins Creed III','Assassins Creed IV: Black Flag','Assassins Creed: Brotherhood','Assassins Creed: Revelations','BioShock'],
    'Year':[2012,np.nan,2013,2010,np.nan,2011]}

df=pd.DataFrame(Games)
print(df)
#using isnull()
print("\n\n",df.isnull())
#using notnull()
print("\n\n",df.notnull())


                            Title    Year
0                       Alan Wake  2012.0
1             Assassins Creed III     NaN
2  Assassins Creed IV: Black Flag  2013.0
3    Assassins Creed: Brotherhood  2010.0
4    Assassins Creed: Revelations     NaN
5                        BioShock  2011.0


    Title   Year
0  False  False
1  False   True
2  False  False
3  False  False
4  False   True
5  False  False


    Title   Year
0   True   True
1   True  False
2   True   True
3   True   True
4   True  False
5   True   True


In [75]:
#Using dropna()
print("\n\n",df.dropna())
#Using fillna(0)
print("\n\n",df.fillna(0))
#Using fillna(method='pad')
print("\n\n",df.fillna(method='pad'))




                             Title    Year
0                       Alan Wake  2012.0
2  Assassins Creed IV: Black Flag  2013.0
3    Assassins Creed: Brotherhood  2010.0
5                        BioShock  2011.0


                             Title    Year
0                       Alan Wake  2012.0
1             Assassins Creed III     0.0
2  Assassins Creed IV: Black Flag  2013.0
3    Assassins Creed: Brotherhood  2010.0
4    Assassins Creed: Revelations     0.0
5                        BioShock  2011.0


                             Title    Year
0                       Alan Wake  2012.0
1             Assassins Creed III  2012.0
2  Assassins Creed IV: Black Flag  2013.0
3    Assassins Creed: Brotherhood  2010.0
4    Assassins Creed: Revelations  2010.0
5                        BioShock  2011.0


C:\Users\rojal\AppData\Local\Temp\ipykernel_11780\975439647.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print("\n\n",df.fillna(method='pad'))


In [76]:
#Using fillna(method='bfill')
print("\n\n",df.fillna(method='bfill'))
#Using replace()
print("\n\n",df.replace(to_replace='BioShock',value='BioShock2'))
#Using interpolate()
df.interpolate(method ='linear', limit_direction ='forward')



                             Title    Year
0                       Alan Wake  2012.0
1             Assassins Creed III  2013.0
2  Assassins Creed IV: Black Flag  2013.0
3    Assassins Creed: Brotherhood  2010.0
4    Assassins Creed: Revelations  2011.0
5                        BioShock  2011.0


                             Title    Year
0                       Alan Wake  2012.0
1             Assassins Creed III     NaN
2  Assassins Creed IV: Black Flag  2013.0
3    Assassins Creed: Brotherhood  2010.0
4    Assassins Creed: Revelations     NaN
5                       BioShock2  2011.0


C:\Users\rojal\AppData\Local\Temp\ipykernel_11780\385218963.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print("\n\n",df.fillna(method='bfill'))
C:\Users\rojal\AppData\Local\Temp\ipykernel_11780\385218963.py:6: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method ='linear', limit_direction ='forward')


Title    Year
0                       Alan Wake  2012.0
1             Assassins Creed III  2012.5
2  Assassins Creed IV: Black Flag  2013.0
3    Assassins Creed: Brotherhood  2010.0
4    Assassins Creed: Revelations  2010.5
5                        BioShock  2011.0

10.Perform the Hierarchical Indexing in the above created dataset.

In [77]:
import pandas as pd
import numpy as np
Games={'Title':['Alan Wake','Assassins Creed III','Assassins Creed IV: Black Flag','Assassins Creed: Brotherhood','Assassins Creed: Revelations','BioShock'],
    'Year':[2012,np.nan,2013,2010,np.nan,2011]}

#Create a dataframe with hierarchical indexing
df=pd.DataFrame(Games)

df.set_index(['Title','Year'],inplace=True)
print(df)

Empty DataFrame
Columns: []
Index: [(Alan Wake, 2012.0), (Assassins Creed III, nan), (Assassins Creed IV: Black Flag, 2013.0), (Assassins Creed: Brotherhood, 2010.0), (Assassins Creed: Revelations, nan), (BioShock, 2011.0)]
